default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: github_action

test:
  <<: *default
  database: github_action
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: angular-webpacker-app_production
  username: angular-webpacker-app
  password: <%= ENV['ANGULAR-WEBPACKER-APP_DATABASE_PASSWORD'] %>
