name: Continuous Integration
on: [push]
jobs:
  rubocop:
    name: 'Rubocop Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Rubocop Linter
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: 'rubocop -c .rubocop.yml'
  system_test:
    name: System Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:9.5
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/github_action
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.ci.yml config/database.yml
          cp config/application.sample.yml config/application.yml
          gem install bundler -v '1.17.3'
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rspec
